apiVersion: v1
kind: Service
metadata:
  name: app_web-service
spec:
  selector:
    app: app_web
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_web
spec:
  selector:
    matchLabels:
      app: app_web
  replicas: 4
  template:
    metadata:
      labels:
        app: app_web
    spec:
      containers:
      - name: app_web
        image: app_web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
