apiVersion: apps/v1
kind: Deployment
metadata:
  name: abhay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abhay
  template:
    metadata:
      labels:
        app: abhay
    spec:
      containers:
      - image: okteto/python:3
        name: abhay

---

apiVersion: v1
kind: Service
metadata:
  name: abhay
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "abhay"
    port: 8080
  selector:
    app: abhay